openapi: 3.0.2
info:
  title: Todo API
  version: "1.0"
  contact:
    name: My name
    email: email@example.com
  description: This API allows user to keep track of their tasks
servers:
  - url: "http://localhost:5001"
    description: Development server
paths:
  /todos:
    post:
      description: Add a todo
      operationId: add-a-todo
      tags:
        - todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                todo-description:
                  type: string
      responses:
        "201":
          description: Created
    get:
      description: Get a list of todos
      operationId: get-todos
      tags:
        - todos
      responses:
        "200":
          description: A JSON array of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    todo-id:
                      type: integer
                    todo-description:
                      type: string
    put:
      summary: Edit a todo
      operationId: put-todos
      responses:
        "200":
          description: OK
      description: |
        Edit a todo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                todo-description:
                  type: string
tags:
  - name: todos
